ALTER TABLE users
    ADD COLUMN IF NOT EXISTS avatar_url VARCHAR(500);

ALTER TABLE users
    ADD COLUMN IF NOT EXISTS github_username VARCHAR(255);

ALTER TABLE users
    ADD COLUMN IF NOT EXISTS plan VARCHAR(20)
        DEFAULT 'FREE';